name: deploy

on:
  workflow_dispatch:
    inputs:
      versionType:
        type: choice
        description: "Semver"
        default: "patch"
        required: true
        options:
          - patch
          - minor
          - major
jobs:
  Build:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
      id-token: write
    environment:
      name: staging
      url: ${{env.PUBLIC_URL}}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Initialize node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Init deployment
        run: echo "PUBLIC_URL=${{vars.PUBLIC_URL}}/main" >> $GITHUB_ENV

      - name: Install dependencies
        run: npm install

      - name: Run Unit tests
        run: npm run build

      - uses: JamesIves/github-pages-deploy-action@v4.4.1
        with:
          folder: ./build
          target-folder: main
          clean: false
